# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/nexmo-jwt/all/nexmo-jwt.rbi
#
# nexmo-jwt-0.1.1

module Vonage
end
class Nexmo::JWT
  def generate; end
  def generator; end
  def generator=(arg0); end
  def iat; end
  def iat=(arg0); end
  def initialize(params = nil); end
  def to_payload; end
  def typ; end
  def typ=(arg0); end
end
class Nexmo::JWTBuilder
  def after_initialize!(builder); end
  def alg; end
  def alg=(arg0); end
  def application_id; end
  def application_id=(arg0); end
  def exp; end
  def exp=(arg0); end
  def initialize(params = nil); end
  def jti; end
  def jti=(arg0); end
  def jwt; end
  def jwt=(arg0); end
  def nbf; end
  def nbf=(arg0); end
  def paths; end
  def paths=(arg0); end
  def private_key; end
  def private_key=(arg0); end
  def self.validate_parameters_not_conflicting(params); end
  def set_application_id(application_id); end
  def set_exp; end
  def set_private_key(private_key); end
  def subject; end
  def subject=(arg0); end
  def ttl; end
  def ttl=(arg0); end
  def validate_application_id(application_id); end
  def validate_not_before(nbf); end
  def validate_paths(acl_paths); end
  def validate_private_key(private_key); end
  def validate_subject(subject); end
  def validate_time_to_live(ttl); end
end
